apiVersion: v1
kind: Service
metadata:
  name: go-webapp
  labels: 
    app: go-webapp
spec:
  selector:
    app: go-webapp
  ports:
  - name: go-webapp
    protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
